include: package:pedantic/analysis_options.yaml
analyzer:
  exclude:
    # Ignore generated files
    - "**/*.g.dart"
    - "lib/src/generated/*.dart"
    - "lib/generated/intl/*.dart"
# linter:
#   rules:

